# TCL File Generated by Component Editor 18.0
# Wed Dec 05 16:09:18 MYT 2018
# DO NOT MODIFY


# 
# pr_control_3port "pr_control_3port" v1.0
#  2018.12.05.16:09:18
# 
# 

# 
# request TCL package from ACDS 18.0
# 
package require -exact qsys 18.0


# 
# module pr_control_3port
# 
set_module_property DESCRIPTION ""
set_module_property NAME pr_control_3port
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME pr_control_3port
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pr_control_conduit_3port
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pr_control_conduit_3port.v VERILOG PATH pr_control_conduit_3port.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL pr_control_conduit_3port
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pr_control_conduit_3port.v VERILOG PATH pr_control_conduit_3port.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point pr_control_0
# 
add_interface pr_control_0 conduit end
set_interface_property pr_control_0 associatedClock ""
set_interface_property pr_control_0 associatedReset ""
set_interface_property pr_control_0 ENABLED true
set_interface_property pr_control_0 EXPORT_OF ""
set_interface_property pr_control_0 PORT_NAME_MAP ""
set_interface_property pr_control_0 CMSIS_SVD_VARIABLES ""
set_interface_property pr_control_0 SVD_ADDRESS_GROUP ""

add_interface_port pr_control_0 freeze_req_0 freeze_req Output 1
add_interface_port pr_control_0 freeze_status_0 freeze_status Input 1
add_interface_port pr_control_0 illegal_req_0 illegal_req Input 2
add_interface_port pr_control_0 reset_0 reset Output 1
add_interface_port pr_control_0 unfreeze_req_0 unfreeze_req Output 1
add_interface_port pr_control_0 unfreeze_status_0 unfreeze_status Input 1


# 
# connection point pr_control_1
# 
add_interface pr_control_1 conduit end
set_interface_property pr_control_1 associatedClock ""
set_interface_property pr_control_1 associatedReset ""
set_interface_property pr_control_1 ENABLED true
set_interface_property pr_control_1 EXPORT_OF ""
set_interface_property pr_control_1 PORT_NAME_MAP ""
set_interface_property pr_control_1 CMSIS_SVD_VARIABLES ""
set_interface_property pr_control_1 SVD_ADDRESS_GROUP ""

add_interface_port pr_control_1 freeze_req_1 freeze_req Output 1
add_interface_port pr_control_1 freeze_status_1 freeze_status Input 1
add_interface_port pr_control_1 illegal_req_1 illegal_req Input 2
add_interface_port pr_control_1 reset_1 reset Output 1
add_interface_port pr_control_1 unfreeze_req_1 unfreeze_req Output 1
add_interface_port pr_control_1 unfreeze_status_1 unfreeze_status Input 1


# 
# connection point pio_conduit
# 
add_interface pio_conduit conduit end
set_interface_property pio_conduit associatedClock ""
set_interface_property pio_conduit associatedReset ""
set_interface_property pio_conduit ENABLED true
set_interface_property pio_conduit EXPORT_OF ""
set_interface_property pio_conduit PORT_NAME_MAP ""
set_interface_property pio_conduit CMSIS_SVD_VARIABLES ""
set_interface_property pio_conduit SVD_ADDRESS_GROUP ""

add_interface_port pio_conduit in_port in_port Output 12
add_interface_port pio_conduit out_port out_port Input 12


# 
# connection point pr_control_2
# 
add_interface pr_control_2 conduit end
set_interface_property pr_control_2 associatedClock ""
set_interface_property pr_control_2 associatedReset ""
set_interface_property pr_control_2 ENABLED true
set_interface_property pr_control_2 EXPORT_OF ""
set_interface_property pr_control_2 PORT_NAME_MAP ""
set_interface_property pr_control_2 CMSIS_SVD_VARIABLES ""
set_interface_property pr_control_2 SVD_ADDRESS_GROUP ""

add_interface_port pr_control_2 freeze_status_2 freeze_status Input 1
add_interface_port pr_control_2 freeze_req_2 freeze_req Output 1
add_interface_port pr_control_2 unfreeze_req_2 unfreeze_req Output 1
add_interface_port pr_control_2 unfreeze_status_2 unfreeze_status Input 1
add_interface_port pr_control_2 reset_2 reset Output 1
add_interface_port pr_control_2 illegal_req_2 illegal_req Input 2

