# TCL File Generated by Component Editor 18.0
# Fri Nov 30 11:22:26 MYT 2018
# DO NOT MODIFY


# 
# pr_handshake "pr_handshake" v1.0
#  2018.11.30.11:22:26
# 
# 

# 
# request TCL package from ACDS 18.0
# 
package require -exact qsys 18.0


# 
# module pr_handshake
# 
set_module_property DESCRIPTION ""
set_module_property NAME pr_handshake
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME pr_handshake
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pr_handshake
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pr_handshake.v VERILOG PATH pr_handshake.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL pr_handshake
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file pr_handshake.v VERILOG PATH pr_handshake.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point pr_handshake
# 
add_interface pr_handshake conduit end
set_interface_property pr_handshake associatedClock ""
set_interface_property pr_handshake associatedReset ""
set_interface_property pr_handshake ENABLED true
set_interface_property pr_handshake EXPORT_OF ""
set_interface_property pr_handshake PORT_NAME_MAP ""
set_interface_property pr_handshake CMSIS_SVD_VARIABLES ""
set_interface_property pr_handshake SVD_ADDRESS_GROUP ""

add_interface_port pr_handshake pr_handshake_start_ack start_ack Output 1
add_interface_port pr_handshake pr_handshake_start_req start_req Input 1
add_interface_port pr_handshake pr_handshake_stop_ack stop_ack Output 1
add_interface_port pr_handshake pr_handshake_stop_req stop_req Input 1


# 
# connection point pr_handshake_1
# 
add_interface pr_handshake_1 conduit end
set_interface_property pr_handshake_1 associatedClock ""
set_interface_property pr_handshake_1 associatedReset ""
set_interface_property pr_handshake_1 ENABLED true
set_interface_property pr_handshake_1 EXPORT_OF ""
set_interface_property pr_handshake_1 PORT_NAME_MAP ""
set_interface_property pr_handshake_1 CMSIS_SVD_VARIABLES ""
set_interface_property pr_handshake_1 SVD_ADDRESS_GROUP ""

add_interface_port pr_handshake_1 pr_handshake_start_ack_1 start_ack Output 1
add_interface_port pr_handshake_1 pr_handshake_start_req_1 start_req Input 1
add_interface_port pr_handshake_1 pr_handshake_stop_ack_1 stop_ack Output 1
add_interface_port pr_handshake_1 pr_handshake_stop_req_1 stop_req Input 1


# 
# connection point pr_handshake_2
# 
add_interface pr_handshake_2 conduit end
set_interface_property pr_handshake_2 associatedClock ""
set_interface_property pr_handshake_2 associatedReset ""
set_interface_property pr_handshake_2 ENABLED true
set_interface_property pr_handshake_2 EXPORT_OF ""
set_interface_property pr_handshake_2 PORT_NAME_MAP ""
set_interface_property pr_handshake_2 CMSIS_SVD_VARIABLES ""
set_interface_property pr_handshake_2 SVD_ADDRESS_GROUP ""

add_interface_port pr_handshake_2 pr_handshake_start_ack_2 start_ack Output 1
add_interface_port pr_handshake_2 pr_handshake_start_req_2 start_req Input 1
add_interface_port pr_handshake_2 pr_handshake_stop_ack_2 stop_ack Output 1
add_interface_port pr_handshake_2 pr_handshake_stop_req_2 stop_req Input 1


# 
# connection point pr_handshake_3
# 
add_interface pr_handshake_3 conduit end
set_interface_property pr_handshake_3 associatedClock ""
set_interface_property pr_handshake_3 associatedReset ""
set_interface_property pr_handshake_3 ENABLED true
set_interface_property pr_handshake_3 EXPORT_OF ""
set_interface_property pr_handshake_3 PORT_NAME_MAP ""
set_interface_property pr_handshake_3 CMSIS_SVD_VARIABLES ""
set_interface_property pr_handshake_3 SVD_ADDRESS_GROUP ""

add_interface_port pr_handshake_3 pr_handshake_start_req_3 start_req Input 1
add_interface_port pr_handshake_3 pr_handshake_start_ack_3 start_ack Output 1
add_interface_port pr_handshake_3 pr_handshake_stop_req_3 stop_req Input 1
add_interface_port pr_handshake_3 pr_handshake_stop_ack_3 stop_ack Output 1

