# TCL File Generated by Component Editor 18.0
# Fri Jan 04 08:16:45 MYT 2019
# DO NOT MODIFY


# 
# pr_reset_source_conduit "pr_reset_source_conduit" v1.0
#  2019.01.04.08:16:45
# 
# 

# 
# request TCL package from ACDS 18.0
# 
package require -exact qsys 18.0


# 
# module pr_reset_source_conduit
# 
set_module_property DESCRIPTION ""
set_module_property NAME pr_reset_source_conduit
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME pr_reset_source_conduit
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pr_reset_source_conduit
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pr_reset_source_conduit.v VERILOG PATH pr_reset_source_conduit.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL pr_reset_source_conduit
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pr_reset_source_conduit.v VERILOG PATH pr_reset_source_conduit.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point s1_reset_source
# 
add_interface s1_reset_source reset start
set_interface_property s1_reset_source associatedClock clock
set_interface_property s1_reset_source associatedDirectReset ""
set_interface_property s1_reset_source associatedResetSinks ""
set_interface_property s1_reset_source synchronousEdges DEASSERT
set_interface_property s1_reset_source ENABLED true
set_interface_property s1_reset_source EXPORT_OF ""
set_interface_property s1_reset_source PORT_NAME_MAP ""
set_interface_property s1_reset_source CMSIS_SVD_VARIABLES ""
set_interface_property s1_reset_source SVD_ADDRESS_GROUP ""

add_interface_port s1_reset_source s1_reset_source reset Output 1


# 
# connection point s2_reset_source
# 
add_interface s2_reset_source reset start
set_interface_property s2_reset_source associatedClock clock
set_interface_property s2_reset_source associatedDirectReset ""
set_interface_property s2_reset_source associatedResetSinks ""
set_interface_property s2_reset_source synchronousEdges DEASSERT
set_interface_property s2_reset_source ENABLED true
set_interface_property s2_reset_source EXPORT_OF ""
set_interface_property s2_reset_source PORT_NAME_MAP ""
set_interface_property s2_reset_source CMSIS_SVD_VARIABLES ""
set_interface_property s2_reset_source SVD_ADDRESS_GROUP ""

add_interface_port s2_reset_source s2_reset_source reset Output 1


# 
# connection point s3_reset_source
# 
add_interface s3_reset_source reset start
set_interface_property s3_reset_source associatedClock clock
set_interface_property s3_reset_source associatedDirectReset ""
set_interface_property s3_reset_source associatedResetSinks ""
set_interface_property s3_reset_source synchronousEdges DEASSERT
set_interface_property s3_reset_source ENABLED true
set_interface_property s3_reset_source EXPORT_OF ""
set_interface_property s3_reset_source PORT_NAME_MAP ""
set_interface_property s3_reset_source CMSIS_SVD_VARIABLES ""
set_interface_property s3_reset_source SVD_ADDRESS_GROUP ""

add_interface_port s3_reset_source s3_reset_source reset Output 1


# 
# connection point s4_reset_source
# 
add_interface s4_reset_source reset start
set_interface_property s4_reset_source associatedClock clock
set_interface_property s4_reset_source associatedDirectReset ""
set_interface_property s4_reset_source associatedResetSinks ""
set_interface_property s4_reset_source synchronousEdges DEASSERT
set_interface_property s4_reset_source ENABLED true
set_interface_property s4_reset_source EXPORT_OF ""
set_interface_property s4_reset_source PORT_NAME_MAP ""
set_interface_property s4_reset_source CMSIS_SVD_VARIABLES ""
set_interface_property s4_reset_source SVD_ADDRESS_GROUP ""

add_interface_port s4_reset_source s4_reset_source reset Output 1


# 
# connection point s5_reset_source
# 
add_interface s5_reset_source reset start
set_interface_property s5_reset_source associatedClock clock
set_interface_property s5_reset_source associatedDirectReset ""
set_interface_property s5_reset_source associatedResetSinks ""
set_interface_property s5_reset_source synchronousEdges DEASSERT
set_interface_property s5_reset_source ENABLED true
set_interface_property s5_reset_source EXPORT_OF ""
set_interface_property s5_reset_source PORT_NAME_MAP ""
set_interface_property s5_reset_source CMSIS_SVD_VARIABLES ""
set_interface_property s5_reset_source SVD_ADDRESS_GROUP ""

add_interface_port s5_reset_source s5_reset_source reset Output 1


# 
# connection point s6_reset_source
# 
add_interface s6_reset_source reset start
set_interface_property s6_reset_source associatedClock clock
set_interface_property s6_reset_source associatedDirectReset ""
set_interface_property s6_reset_source associatedResetSinks ""
set_interface_property s6_reset_source synchronousEdges DEASSERT
set_interface_property s6_reset_source ENABLED true
set_interface_property s6_reset_source EXPORT_OF ""
set_interface_property s6_reset_source PORT_NAME_MAP ""
set_interface_property s6_reset_source CMSIS_SVD_VARIABLES ""
set_interface_property s6_reset_source SVD_ADDRESS_GROUP ""

add_interface_port s6_reset_source s6_reset_source reset Output 1


# 
# connection point s7_reset_source
# 
add_interface s7_reset_source reset start
set_interface_property s7_reset_source associatedClock clock
set_interface_property s7_reset_source associatedDirectReset ""
set_interface_property s7_reset_source associatedResetSinks ""
set_interface_property s7_reset_source synchronousEdges DEASSERT
set_interface_property s7_reset_source ENABLED true
set_interface_property s7_reset_source EXPORT_OF ""
set_interface_property s7_reset_source PORT_NAME_MAP ""
set_interface_property s7_reset_source CMSIS_SVD_VARIABLES ""
set_interface_property s7_reset_source SVD_ADDRESS_GROUP ""

add_interface_port s7_reset_source s7_reset_source reset Output 1


# 
# connection point s8_reset_source
# 
add_interface s8_reset_source reset start
set_interface_property s8_reset_source associatedClock clock
set_interface_property s8_reset_source associatedDirectReset ""
set_interface_property s8_reset_source associatedResetSinks ""
set_interface_property s8_reset_source synchronousEdges DEASSERT
set_interface_property s8_reset_source ENABLED true
set_interface_property s8_reset_source EXPORT_OF ""
set_interface_property s8_reset_source PORT_NAME_MAP ""
set_interface_property s8_reset_source CMSIS_SVD_VARIABLES ""
set_interface_property s8_reset_source SVD_ADDRESS_GROUP ""

add_interface_port s8_reset_source s8_reset_source reset Output 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1


# 
# connection point conduit
# 
add_interface conduit conduit end
set_interface_property conduit associatedClock ""
set_interface_property conduit associatedReset ""
set_interface_property conduit ENABLED true
set_interface_property conduit EXPORT_OF ""
set_interface_property conduit PORT_NAME_MAP ""
set_interface_property conduit CMSIS_SVD_VARIABLES ""
set_interface_property conduit SVD_ADDRESS_GROUP ""

add_interface_port conduit out_port export Input 9

