# TCL File Generated by Component Editor 18.0
# Thu Dec 13 15:12:26 MYT 2018
# DO NOT MODIFY


# 
# security_filter "security_filter" v0
#  2018.12.13.15:12:26
# 
# 

# 
# request TCL package from ACDS 18.0
# 
package require -exact qsys 18.0


# 
# module security_filter
# 
set_module_property DESCRIPTION ""
set_module_property NAME security_filter
set_module_property VERSION 0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME security_filter
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL security_filter
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file security_filter.sv SYSTEM_VERILOG PATH security_filter.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL security_filter
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file security_filter.sv SYSTEM_VERILOG PATH security_filter.sv


# 
# parameters
# 
add_parameter DROP_ADDR INTEGER 255
set_parameter_property DROP_ADDR DEFAULT_VALUE 255
set_parameter_property DROP_ADDR DISPLAY_NAME DROP_ADDR
set_parameter_property DROP_ADDR UNITS None
set_parameter_property DROP_ADDR ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DROP_ADDR HDL_PARAMETER true
add_parameter S0_ADDR INTEGER 0
set_parameter_property S0_ADDR DEFAULT_VALUE 0
set_parameter_property S0_ADDR DISPLAY_NAME S0_ADDR
set_parameter_property S0_ADDR UNITS None
set_parameter_property S0_ADDR ALLOWED_RANGES -2147483648:2147483647
set_parameter_property S0_ADDR HDL_PARAMETER true
add_parameter S1_ADDR INTEGER 0
set_parameter_property S1_ADDR DEFAULT_VALUE 0
set_parameter_property S1_ADDR DISPLAY_NAME S1_ADDR
set_parameter_property S1_ADDR UNITS None
set_parameter_property S1_ADDR ALLOWED_RANGES -2147483648:2147483647
set_parameter_property S1_ADDR HDL_PARAMETER true
add_parameter S2_ADDR INTEGER 0 ""
set_parameter_property S2_ADDR DEFAULT_VALUE 0
set_parameter_property S2_ADDR DISPLAY_NAME S2_ADDR
set_parameter_property S2_ADDR UNITS None
set_parameter_property S2_ADDR ALLOWED_RANGES -2147483648:2147483647
set_parameter_property S2_ADDR DESCRIPTION ""
set_parameter_property S2_ADDR HDL_PARAMETER true
add_parameter S3_ADDR INTEGER 0
set_parameter_property S3_ADDR DEFAULT_VALUE 0
set_parameter_property S3_ADDR DISPLAY_NAME S3_ADDR
set_parameter_property S3_ADDR UNITS None
set_parameter_property S3_ADDR ALLOWED_RANGES -2147483648:2147483647
set_parameter_property S3_ADDR HDL_PARAMETER true
add_parameter S4_ADDR INTEGER 0
set_parameter_property S4_ADDR DEFAULT_VALUE 0
set_parameter_property S4_ADDR DISPLAY_NAME S4_ADDR
set_parameter_property S4_ADDR UNITS None
set_parameter_property S4_ADDR ALLOWED_RANGES -2147483648:2147483647
set_parameter_property S4_ADDR HDL_PARAMETER true
add_parameter S5_ADDR INTEGER 0
set_parameter_property S5_ADDR DEFAULT_VALUE 0
set_parameter_property S5_ADDR DISPLAY_NAME S5_ADDR
set_parameter_property S5_ADDR UNITS None
set_parameter_property S5_ADDR ALLOWED_RANGES -2147483648:2147483647
set_parameter_property S5_ADDR HDL_PARAMETER true
add_parameter S6_ADDR INTEGER 0
set_parameter_property S6_ADDR DEFAULT_VALUE 0
set_parameter_property S6_ADDR DISPLAY_NAME S6_ADDR
set_parameter_property S6_ADDR UNITS None
set_parameter_property S6_ADDR ALLOWED_RANGES -2147483648:2147483647
set_parameter_property S6_ADDR HDL_PARAMETER true
add_parameter S7_ADDR INTEGER 0
set_parameter_property S7_ADDR DEFAULT_VALUE 0
set_parameter_property S7_ADDR DISPLAY_NAME S7_ADDR
set_parameter_property S7_ADDR UNITS None
set_parameter_property S7_ADDR ALLOWED_RANGES -2147483648:2147483647
set_parameter_property S7_ADDR HDL_PARAMETER true
add_parameter S8_ADDR INTEGER 0
set_parameter_property S8_ADDR DEFAULT_VALUE 0
set_parameter_property S8_ADDR DISPLAY_NAME S8_ADDR
set_parameter_property S8_ADDR UNITS None
set_parameter_property S8_ADDR ALLOWED_RANGES -2147483648:2147483647
set_parameter_property S8_ADDR HDL_PARAMETER true
add_parameter DATA_SIZE INTEGER 32
set_parameter_property DATA_SIZE DEFAULT_VALUE 32
set_parameter_property DATA_SIZE DISPLAY_NAME DATA_SIZE
set_parameter_property DATA_SIZE UNITS None
set_parameter_property DATA_SIZE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_SIZE HDL_PARAMETER true
add_parameter AVMM_ADDR_SIZE INTEGER 16
set_parameter_property AVMM_ADDR_SIZE DEFAULT_VALUE 16
set_parameter_property AVMM_ADDR_SIZE DISPLAY_NAME AVMM_ADDR_SIZE
set_parameter_property AVMM_ADDR_SIZE UNITS None
set_parameter_property AVMM_ADDR_SIZE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AVMM_ADDR_SIZE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressGroup 0
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clock_sink
set_interface_property s0 associatedReset reset_sink
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 bridgedAddressOffset ""
set_interface_property s0 bridgesToMaster m0
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 maximumPendingWriteTransactions 0
set_interface_property s0 minimumResponseLatency 1
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 transparentBridge false
set_interface_property s0 waitrequestAllowance 0
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 avs_s0_write write Input 1
add_interface_port s0 avs_s0_writedata writedata Input "((DATA_SIZE - 1)) - (0) + 1"
add_interface_port s0 avs_s0_waitrequest waitrequest Output 1
add_interface_port s0 avs_s0_address address Input "((AVMM_ADDR_SIZE - 1)) - (0) + 1"
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point m0
# 
add_interface m0 avalon start
set_interface_property m0 addressGroup 0
set_interface_property m0 addressUnits SYMBOLS
set_interface_property m0 associatedClock clock_sink
set_interface_property m0 associatedReset reset_sink
set_interface_property m0 bitsPerSymbol 8
set_interface_property m0 burstOnBurstBoundariesOnly false
set_interface_property m0 burstcountUnits WORDS
set_interface_property m0 doStreamReads false
set_interface_property m0 doStreamWrites false
set_interface_property m0 holdTime 0
set_interface_property m0 linewrapBursts false
set_interface_property m0 maximumPendingReadTransactions 0
set_interface_property m0 maximumPendingWriteTransactions 0
set_interface_property m0 minimumResponseLatency 1
set_interface_property m0 readLatency 0
set_interface_property m0 readWaitTime 1
set_interface_property m0 setupTime 0
set_interface_property m0 timingUnits Cycles
set_interface_property m0 waitrequestAllowance 0
set_interface_property m0 writeWaitTime 0
set_interface_property m0 ENABLED true
set_interface_property m0 EXPORT_OF ""
set_interface_property m0 PORT_NAME_MAP ""
set_interface_property m0 CMSIS_SVD_VARIABLES ""
set_interface_property m0 SVD_ADDRESS_GROUP ""

add_interface_port m0 avm_m0_address address Output "((AVMM_ADDR_SIZE - 1)) - (0) + 1"
add_interface_port m0 avm_m0_waitrequest waitrequest Input 1
add_interface_port m0 avm_m0_write write Output 1
add_interface_port m0 avm_m0_writedata writedata Output "((DATA_SIZE - 1)) - (0) + 1"


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clock_clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink reset_reset reset_n Input 1


# 
# connection point avl_csr
# 
add_interface avl_csr avalon end
set_interface_property avl_csr addressGroup 0
set_interface_property avl_csr addressUnits WORDS
set_interface_property avl_csr associatedClock clock_sink
set_interface_property avl_csr associatedReset reset_sink
set_interface_property avl_csr bitsPerSymbol 8
set_interface_property avl_csr bridgedAddressOffset ""
set_interface_property avl_csr bridgesToMaster ""
set_interface_property avl_csr burstOnBurstBoundariesOnly false
set_interface_property avl_csr burstcountUnits WORDS
set_interface_property avl_csr explicitAddressSpan 0
set_interface_property avl_csr holdTime 0
set_interface_property avl_csr linewrapBursts false
set_interface_property avl_csr maximumPendingReadTransactions 0
set_interface_property avl_csr maximumPendingWriteTransactions 0
set_interface_property avl_csr minimumResponseLatency 1
set_interface_property avl_csr readLatency 0
set_interface_property avl_csr readWaitTime 1
set_interface_property avl_csr setupTime 0
set_interface_property avl_csr timingUnits Cycles
set_interface_property avl_csr transparentBridge false
set_interface_property avl_csr waitrequestAllowance 0
set_interface_property avl_csr writeWaitTime 0
set_interface_property avl_csr ENABLED true
set_interface_property avl_csr EXPORT_OF ""
set_interface_property avl_csr PORT_NAME_MAP ""
set_interface_property avl_csr CMSIS_SVD_VARIABLES ""
set_interface_property avl_csr SVD_ADDRESS_GROUP ""

add_interface_port avl_csr avl_csr_write write Input 1
add_interface_port avl_csr avl_csr_read read Input 1
add_interface_port avl_csr avl_csr_addr address Input 1
add_interface_port avl_csr avl_csr_rddata readdata Output "((DATA_SIZE - 1)) - (0) + 1"
add_interface_port avl_csr avl_csr_wrdata writedata Input "((DATA_SIZE - 1)) - (0) + 1"
set_interface_assignment avl_csr embeddedsw.configuration.isFlash 0
set_interface_assignment avl_csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avl_csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avl_csr embeddedsw.configuration.isPrintableDevice 0

