# TCL File Generated by Component Editor 18.0
# Thu Sep 20 10:28:13 MYT 2018
# DO NOT MODIFY


# 
# user0_logic_wrapper "user0_logic_wrapper" v1.0
#  2018.09.20.10:28:13
# 
# 

# 
# request TCL package from ACDS 18.0
# 
package require -exact qsys 18.0


# 
# module user0_logic_wrapper
# 
set_module_property DESCRIPTION ""
set_module_property NAME user0_logic_wrapper
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME user0_logic_wrapper
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL user0_logic_wrapper
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file user0_logic_wrapper.sv SYSTEM_VERILOG PATH user0_logic_wrapper.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressGroup 0
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock_sink
set_interface_property avalon_master associatedReset reset_sink
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master minimumResponseLatency 1
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master waitrequestAllowance 0
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master avmm_master_waitrequest waitrequest Input 1
add_interface_port avalon_master avmm_master_readdata readdata Input 32
add_interface_port avalon_master avmm_master_readdatavalid readdatavalid Input 1
add_interface_port avalon_master avmm_master_burstcount burstcount Output 1
set_port_property avmm_master_burstcount VHDL_TYPE STD_LOGIC_VECTOR
add_interface_port avalon_master avmm_master_writedata writedata Output 32
add_interface_port avalon_master avmm_master_address address Output 20
add_interface_port avalon_master avmm_master_write write Output 1
add_interface_port avalon_master avmm_master_read read Output 1
add_interface_port avalon_master avmm_master_byteenable byteenable Output 4


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink pr_region_clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink pr_logic_rst reset Input 1


# 
# connection point pr_handshake
# 
add_interface pr_handshake conduit end
set_interface_property pr_handshake associatedClock ""
set_interface_property pr_handshake associatedReset ""
set_interface_property pr_handshake ENABLED true
set_interface_property pr_handshake EXPORT_OF ""
set_interface_property pr_handshake PORT_NAME_MAP ""
set_interface_property pr_handshake CMSIS_SVD_VARIABLES ""
set_interface_property pr_handshake SVD_ADDRESS_GROUP ""

add_interface_port pr_handshake pr_handshake_start_ack start_ack Output 1
add_interface_port pr_handshake pr_handshake_start_req start_req Input 1
add_interface_port pr_handshake pr_handshake_stop_ack stop_ack Output 1
add_interface_port pr_handshake pr_handshake_stop_req stop_req Input 1


# 
# connection point sld_host
# 
add_interface sld_host conduit end
set_interface_property sld_host associatedClock ""
set_interface_property sld_host associatedReset ""
set_interface_property sld_host ENABLED true
set_interface_property sld_host EXPORT_OF ""
set_interface_property sld_host PORT_NAME_MAP ""
set_interface_property sld_host CMSIS_SVD_VARIABLES ""
set_interface_property sld_host SVD_ADDRESS_GROUP ""

add_interface_port sld_host ena ena Input 1
add_interface_port sld_host tck tck Input 1
add_interface_port sld_host tdi tdi Input 1
add_interface_port sld_host tdo tdo Output 1
add_interface_port sld_host tms tms Input 1
add_interface_port sld_host vir_tdi vir_tdi Input 1

